inherit_gem:
  rubocop-rails-omakase: rubocop.yml

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-minitest
  - rubocop-capybara

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'

Style/ArgumentsForwarding:
  Enabled: false

Style/Documentation:
  Enabled: false
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'previews/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Metrics/ParameterLists:
  Exclude:
    - 'app/components/**/*'

Metrics/MethodLength:
  Max: 50

Metrics/BlockLength:
  Max: 75
  Exclude:
    - 'lib/tasks/**/*.rake'
    - 'app/**/concerns/*'

Layout/LineLength:
  Max: 180
  Exclude:
    - 'test/models/card/**/*_test.rb'
