default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "*"
      threads: 1
      polling_interval: 2
    - queues: storage_analysis,storage_purge
      threads: 10
      polling_interval: 2
    - queues: documents
      threads: 5
      polling_interval: 2
    - queues: imports
      threads: 5
      polling_interval: 2
    - queues: real_time,background
      threads: 1
      polling_interval: 0.1
      processes: 1

development:
  <<: *default
  database: queue

test:
  <<: *default
  database: queue

production:
  <<: *default
  database: queue
