name: Deploy to Fly
on:
  push:
    tags: [ "main.*" ]

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    permissions:
      deployments: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: start deployment
        uses: bobheadxi/deployments@v1.5.0
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production
          deployment_id: ${{ github.event.deployment.id }}
      - name: release to Sentry
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          # SENTRY_URL: https://sentry.io/
        with:
          version: ${{ github.ref }}
          environment: production
      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Set release to Fly
        run: flyctl secrets set RELEASE_VERSION=${{ github.ref }}
      - name: Deploy to Fly
        run: flyctl deploy --remote-only
      - name: update deployment status
        uses: bobheadxi/deployments@v1.5.0
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env: ${{ steps.deployment.outputs.env }}
